version: '3'

volumes:
  pg_data_production:
  static_volume:
  media_volume:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data_production:/var/lib/postgresql/data

  backend:
    image: vismar/kittygram_backend
    env_file: .env
    volumes:
    - media_volume:/media
    - static_volume:/backend_static

  frontend:
    env_file: .env
    image: vismar/kittygram_frontend
    command: cp -r /app/build/. /static/
    volumes:
      - static_volume:/static

  gateway:
    image: vismar/kittygram_gateway
    env_file: .env
    ports:
      - 9000:80
    volumes:
      - static_volume:/static
      - media_volume:/media