version: '3'

volumes:
  pg_data_production:
  static_volume:
  media_volume:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data_production:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    image: vismar/kittygram_backend
    env_file: .env
    volumes:
      - media_volume:/media
      - static_volume:/backend_static
    depends_on:
      - db

  frontend:
    image: vismar/kittygram_frontend
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static_volume:/frontend_static

  gateway:
    image: vismar/kittygram_gateway
    env_file: .env
    ports:
      - 9000:80
    volumes:
      - static_volume:/staticfiles/
      - media_volume:/media
    depends_on:
      - backend
      - frontend